name: Build the Docker images

on:
  # Only trigger the workflow when there is a PR on the master branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # checkout the repository in the ubuntu-latest environment
    - uses: actions/checkout@v3

    - name: Build the Docker images
      run: docker compose --file build-docker-compose.yml --env-file template.env build 
